### ISSUE TITLE
EventAggregator.Blazor 1.1.0, blazor preview 8: IL linker fails during compilation

### ISSUE THREAD

**Issue by jirikanda** [mikoskinen/Blazor.EventAggregator#2]
### Symptom
2>Fatal error in IL Linker
2>
2>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher::DispatchEvent(Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher/BrowserEventDescriptor,System.String)' in assembly: 'Microsoft.AspNetCore.Components.Browser.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task Microsoft.AspNetCore.Components.Rendering.Renderer::DispatchEventAsync(System.Int32,Microsoft.AspNetCore.Components.UIEventArgs)
2>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
2>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
2>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
2>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   --- End of inner exception stack trace ---
2>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
2>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
2>   at Mono.Linker.Steps.MarkStep.Process()
2>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
2>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
2>   at Mono.Linker.Pipeline.Process(LinkContext context)
2>   at Mono.Linker.Driver.Run(ILogger customLogger)
2>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
2>   at Mono.Linker.Driver.Main(String[] args)

### Reprosteps
Just add (reference) NuGet package EventAggregator.Blazor 1.1.0 to project and build the project.

### Enviroment
.NET Core 3.0.100-preview8-013656
Microsoft.AspNetCore.Blazor 3.0.0-preview8

**Comment by jirikanda** [comment]
Building EventAggregator.Blazor locally and referencing a compiled dll solves the problem. It is not pretty sure the issue is connected to EventAggregator.Blazor. There could be an issue in the linker.

**Comment by dradovic** [comment]
When are you planning to publish the new NuGet with this fix?

**Comment by mikoskinen** [comment]
I've submitted the latest package. It should be available shortly: https://www.nuget.org/packages/EventAggregator.Blazor/1.2.0

**Comment by dradovic** [comment]
Thank you very much.
